### ISSUE TITLE
Where to install on fedora linux

### ISSUE THREAD

**Issue by Benjydenjy** [clifford269/FrutigerFX#2]
Where to install on fedora linux

**Comment by clifford269** [comment]
Linux will require specific modifications in the code. Furthermore, it is not a singular operating system but has dozens of flavours. I am currently unable to spare time to installing it and testing on it.

**Comment by Aworldc** [comment]
![image](https://github.com/user-attachments/assets/aac2300d-2311-47b8-b42d-6cf251e136a0)
i got this far on hyprland on nixos. i went to [about:support](about:support), and under the Profile Directory section i clicked on open directory, then dumped this repo's chrome folder in there. i then went to [about:config](about:config) and set toolkit.legacyUserProfileCustomizations.stylesheets to true.

it probably doesn't help that i'm using ff 130 instead of ff esr/115.

**Comment by Aworldc** [comment]
Ok, using esr/115 doesn't fix anything.
